name: Randomize Profile GIF

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  randomize:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Random GIF Picker
        run: |
          # Load gifs
          GIFS=("./assets/lamp-1.gif" "./assets/lamp-2.gif" "./assets/lamp-3.gif")
          
          # Pick one randomly
          SELECTED_GIF=${GIFS[$RANDOM % ${#GIFS[@]}]}
          echo "Selected gif: $SELECTED_GIF"

          # Replace the content
          sed -i "//,//c\\n<img src=\"$SELECTED_GIF\" width=\"100%\" alt=\"Dynamic Lamp\" />\n" README.md

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Random Gif Picker" || exit 0
          git push